### ISSUE TITLE
误判问题

### ISSUE THREAD

**Issue by huskyy8y8** [PA733/MLKD#1]
玩家攻击僵尸即被判断为killaura，也有其他类似问题玩家反应误判
需要提供什么资料给您修复？

**Comment by PA733** [comment]
更新到新版，提交plugins/MLKAD/log文件夹内，对应的事件记录即可。
感谢您的反馈

**Comment by huskyy8y8** [comment]
攻击豬

HitomiGozila,21de6247-51d9-34d7-946e-742a5b1e19b3,1691159786297
distance,angle,result
3.35465,1.26421,0.898324
5.42079,0.618526,0.982238
4.91294,0.519602,0.820655
3.29703,0.734958,0.265916
2.74894,0.562108,0.15724
3.62,0.925359,0.641127
2.64916,0.294044,0.142427
2.22911,0.496391,0.147945
3.80929,0.705524,0.415467
3.42448,0.621092,0.223022

**Comment by PA733** [comment]
感谢您的反馈，我们正在分析此数据。
此外，我们即将发布0.2.1版本，提供关闭command（踢人）功能的选项，请您稍作等待

**Comment by PA733** [comment]
抱歉，我发现您提交的数据中包含玩家敏感信息
为了保护隐私，我已将您的comment删去。
相关数据已记录，分析结果将在此回复。

**Comment by PA733** [comment]
<img width="585" alt="image" src="https://github.com/PA733/MLKAD/assets/67588574/2e2ec560-97e3-4c0a-ac0c-20d922b36433">

您好，经过分析，我们暂时**不能排除**此玩家的作弊嫌疑：如图，在您提供的样本中，该玩家两次攻击到了距自己4.5格以外的距离，并且多次攻击角度过大。建议您观察该玩家一段时间。
请注意，分析结果仅供参考，只代表我自己观点。
如果您有更多样本，欢迎提交。我们很高兴为您分析相关数据。
有关本插件的工作原理，您可以前往 [LiteLoader Blog](https://blog.litebds.com/2023/07/31/machine-learning-killaura-detect/) 阅读。
